version: '3.8'
services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - stout
    container_name: frontend
    
  backend:
    build: backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - stout
    container_name: backend

networks:
  stout:
    driver: bridge